from django.urls import path
from .views import *
# 正在部署的应用的名称
app_name = 'roomhubSite'

from django.urls import path
from .views import *
# 正在部署的应用的名称
app_name = 'roomhubSite'
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('login/', login, name='login'),
	path('register/', register, name='register'),
	path('logout/', logout, name='logout'),
    path('uploadinfo/', uploadinfo, name='uploadinfo'),
    path('getuser/', getuser, name='getuser'),
    path('upload_avatars/', upload_avatars, name='upload_avatars'),
    path('room_add/', room_add, name='room_add'),
    path('fix/', fix, name='fix'),
    path('upload_image/', upload_image, name='upload_image'),
    path('delete_image/', delete_image, name='delete_image'),
    path('allhouse/', allhouse, name='allhouse'),
    path('search/', search, name='search'),
    path('house_collect/', house_collect, name='house_collect'),
    path('house_uncollect/', house_uncollect, name='house_uncollect'),
    path('collect_list/', collect_list, name='collect_list'),
    path('room_update/', room_update, name='room_update'),
    path('roominfo/', roominfo, name='roominfo'),
    path('charge/', charge, name='charge'),
    path('apply/', apply, name='apply'),
    path('humancheck/', humancheck, name='humancheck'),
    path('generate_order/', generate_order, name='generate_order'),
    path('orderlist/', orderlist, name='orderlist'),
    path('orderinfo/', orderinfo, name='orderinfo'),
    path('order_delete/', order_delete, name='order_delete'),
    path('extension/', extension, name='extension'),
    path('uploadinfo_M/', uploadinfo_M, name='uploadinfo_M'),
    path('user_info/', user_info, name='user_info'),
    path('user_list/', user_list, name='user_list'),
    path('contract_list_M/', contract_list_M, name='contract_list_M'),
    path('contract_list_U/', contract_list_U, name='contract_list_U'),
    path('contract_info_M/', contract_info_M, name='contract_info_M'),
    path('contract_delete/', contract_delete, name='contract_delete'),
    path('generate_repair/', generate_repair, name='generate_repair'),
    path('arrange/', arrange, name='arrange'),
    path('repair_list/', repair_list, name='repair_list'),
    path('repair_info/', repair_info, name='repair_info'),
    path('repair_list_U/', repair_list_U, name='repair_list_U'),
    path('repair_list_M/',repair_list_M, name='repair_list_M'),
    path('repair_info_U/', repair_info_U, name='repair_info_U'),
    path('repair_delete_U/', repair_delete_U, name='repair_delete_U'),
    path('generate_complaint/', generate_complaint, name='generate_complaint'),
    path('complaint_list_U/', complaint_list_U, name='complaint_list_U'),
    path('complaint_info_U/', complaint_info_U, name='complaint_info_U'),
    path('complaint_delete_U/', complaint_delete_U, name='complaint_delete_U'),
    path('complaint_list/', complaint_list, name='complaint_list'),
    path('complaint_info/', complaint_info, name='complaint_info'),
    path('reply/', reply, name='reply'),
    path('addMaster/', addMaster, name='addMaster'),
    path('delMaster/', delMaster, name='delMaster'),
    path('reply_G/', reply_G, name='reply_G'),
    path('comment/', comment, name='comment'),
    path('house_list_U/', house_list_U, name='house_list_U'),
    path('recommend/', recommend, name='recommend'),
    path('changepassword/', changepassword, name='changepassword'),
    path('gen_pdf/', gen_pdf, name='gen_pdf'),
    path('download_template/', download_template, name='download_template'),
    path('first_page/', first_page, name='first_page'),
    path('worker_list/', worker_list, name='worker_list'),
    path('email_forget/', email_forget, name='email_forget'),
    path('forgetpassword/', forgetpassword, name='forgetpassword'),
    path('email_register/', email_register, name='email_register'),
    path('allhouse_M/', allhouse_M, name='allhouse_M'),
    path('repair_list_N/', repair_list_N, name='repair_list_N'),
    path('upload_avatars_M/', upload_avatars_M, name='upload_avatars_M'),
    path('orderlist_M/', orderlist_M, name='orderlist_M'),
    path('orderlist_M_1/', orderlist_M_1, name='orderlist_M_1'),
    path('complaint_list_M_1/', complaint_list_M_1, name='complaint_list_M_1'),
    path('get/', get, name='get'),
    path('put/', put, name='put'),
    path('generate_order_M/', generate_order_M, name='generate_order_M'),
    path('upload_contract/', upload_contract, name='upload_contract'),
  
    
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
